spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eiv-exam
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true # Opcional, para ver las consultas SQL generadas por Hibernate

application:
  security:
    jwt:
      expiration: 86400000 # a day

#server:
#  port: 8085